apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin:latest
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql-service.default
        ports:
        - containerPort: 80
          name: phpmyadmin
